# Numpy

In [2]:
'''
NumPy (Numerical Python) is a Python library used to work with:
> Arrays (like lists but faster and more powerful)
> Math operations on arrays
> Data science, machine learning, scientific computing

Why use NumPy?
> Fast
> Uses less memory
> Works with large data
> Built-in functions for math, stats, random numbers, etc.

NumPy Learning Structure with Practice

🔰 Stage 1: Basics & Setup
> Installing and importing NumPy
> Creating arrays (array, zeros, ones, full, eye, arange, linspace)
> Checking attributes (shape, ndim, size, dtype, itemsize)

Practice:
Create arrays of different shapes.
Print their attributes.

🧮 Stage 2: Indexing, Slicing & Reshaping
> Indexing and slicing (1D, 2D arrays)
> Boolean indexing and fancy indexing
> Reshape, flatten, transpose (reshape, ravel, flatten, T)

Practice:
Slice rows and columns.
Extract all even numbers from an array using boolean indexing.

➕ Stage 3: Math & Statistics
> Element-wise operations (+, -, *, /, **)
> Aggregate functions (sum, mean, std, min, max, argmax)
> Axis-based operations (e.g., np.sum(arr, axis=1))

Practice:
Compare row-wise and column-wise statistics.

🔁 Stage 4: Broadcasting
> What is broadcasting?
> Broadcasting rules
> Operations with different-shaped arrays

Practice:
Add a row vector to a 2D matrix using broadcasting.

🎲 Stage 5: Random Numbers
> np.random.rand(), randn(), randint()
> choice(), shuffle(), seed()

Practice:
Generate random test data.
Shuffle and sample from arrays.

📐 Stage 6: Linear Algebra
> Dot product (np.dot, @)
> Matrix multiplication
> Transpose, inverse, determinant
> Eigenvalues and eigenvectors (np.linalg)

Practice:
Multiply two matrices.
Invert a 2x2 matrix.

⚙️ Stage 7: Advanced Operations
> Stacking and splitting arrays (hstack, vstack, split)
> Sorting (sort, argsort)
> Unique values and set operations (unique, intersect1d)

Practice:
Sort rows and columns.
Find common elements between arrays.

📦 Stage 8: Practical Projects
 NumPy in:
Temperature Data Analysis
Image as array
Simple Linear Regression (NumPy only)
Simulations (dice, cards)

🧪 Stage 9: Practice & Mini Projects
> Weekly quizzes
> Build mini projects using NumPy only
> Solve real-world problems using NumPy
'''

'\nNumPy (Numerical Python) is a Python library used to work with:\n> Arrays (like lists but faster and more powerful)\n> Math operations on arrays\n> Data science, machine learning, scientific computing\n\nWhy use NumPy?\n> Fast\n> Uses less memory\n> Works with large data\n> Built-in functions for math, stats, random numbers, etc.\n\nNumPy Learning Structure with Practice\n\n🔰 Stage 1: Basics & Setup\n> Installing and importing NumPy\n> Creating arrays (array, zeros, ones, full, eye, arange, linspace)\n> Checking attributes (shape, ndim, size, dtype, itemsize)\n\nPractice:\nCreate arrays of different shapes.\nPrint their attributes.\n\n🧮 Stage 2: Indexing, Slicing & Reshaping\n> Indexing and slicing (1D, 2D arrays)\n> Boolean indexing and fancy indexing\n> Reshape, flatten, transpose (reshape, ravel, flatten, T)\n\nPractice:\nSlice rows and columns.\nExtract all even numbers from an array using boolean indexing.\n\n➕ Stage 3: Math & Statistics\n> Element-wise operations (+, -, *, /, 

# Basics and Setup

In [4]:
#Importing NumPy
import numpy as np

In [5]:
#Creating Arrays

# 1. Using np.array()
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
print("1. np.array()")
print("1D array:", a)
print("2D array:\n", b, "\n")

# 2. Using np.zeros() and np.ones()
print("2. np.zeros() and np.ones()")
print("2x3 matrix of 0s:\n", np.zeros((2, 3)))
print("1D array of 3 ones:", np.ones((3,)), "\n")

# 3. Using np.full()
print("3. np.full()")
print("2x2 array filled with 9s:\n", np.full((2, 2), 9), "\n")

# 4. Using np.eye()
print("4. np.eye()")
print("3x3 identity matrix:\n", np.eye(3), "\n")

# 5. Using np.arange()
print("5. np.arange()")
print("Range from 0 to 10 with step 2:", np.arange(0, 10, 2), "\n")

# 6. Using np.linspace()
print("6. np.linspace()")
print("5 evenly spaced numbers from 0 to 1:", np.linspace(0, 1, 5), "\n")

#Array Attributes

# 7. Array Attributes
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("7. Array Attributes")
print("Array:\n", arr)
print("Shape:", arr.shape)         # (2, 3)
print("Dimensions (ndim):", arr.ndim)  # 2
print("Total elements (size):", arr.size)  # 6
print("Data type (dtype):", arr.dtype)    # int64 or int32
print("Item size (bytes):", arr.itemsize) # Usually 4 or 8 depending on dtype

1. np.array()
1D array: [1 2 3]
2D array:
 [[1 2]
 [3 4]] 

2. np.zeros() and np.ones()
2x3 matrix of 0s:
 [[0. 0. 0.]
 [0. 0. 0.]]
1D array of 3 ones: [1. 1. 1.] 

3. np.full()
2x2 array filled with 9s:
 [[9 9]
 [9 9]] 

4. np.eye()
3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

5. np.arange()
Range from 0 to 10 with step 2: [0 2 4 6 8] 

6. np.linspace()
5 evenly spaced numbers from 0 to 1: [0.   0.25 0.5  0.75 1.  ] 

7. Array Attributes
Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions (ndim): 2
Total elements (size): 6
Data type (dtype): int64
Item size (bytes): 8


# Indexing, Slicing & Reshaping

In [6]:
import numpy as np

# 1. Indexing (Access elements)
print("1. Indexing")
a = np.array([10, 20, 30])
print("a =", a)
print("a[0] =", a[0])     # 10
print("a[-1] =", a[-1])   # 30 (last element)

b = np.array([[1, 2], [3, 4]])
print("\nb =\n", b)
print("b[0, 1] =", b[0, 1])  # 2 → row 0, column 1

# 2. Slicing (Extract parts)
print("\n2. Slicing")
a = np.array([10, 20, 30, 40])
print("a =", a)
print("a[1:3] =", a[1:3])  # [20 30]
print("a[:2] =", a[:2])    # [10 20]

b = np.array([[1, 2, 3], [4, 5, 6]])
print("\nb =\n", b)
print("b[:, 1] =", b[:, 1])  # [2 5] → all rows, column 1
print("b[0, :] =", b[0, :])  # [1 2 3] → row 0, all columns

# 3. Boolean Indexing
print("\n3. Boolean Indexing")
a = np.array([5, 10, 15, 20])
print("a =", a)
print("a[a > 10] =", a[a > 10])  # [15 20]

# 4. Fancy Indexing
print("\n4. Fancy Indexing")
a = np.array([10, 20, 30, 40])
print("a =", a)
print("a[[0, 2]] =", a[[0, 2]])  # [10 30]

# 5. Reshape & Flatten
print("\n5. Reshape & Flatten")
a = np.array([[1, 2], [3, 4], [5, 6]])
print("Original array:\n", a)
print("Shape:", a.shape)             # (3, 2)
print("Reshaped to 2x3:\n", a.reshape(2, 3))  # Reshape to 2x3
print("Flattened array:", a.flatten())       # [1 2 3 4 5 6]

# 6. Transpose
print("\n6. Transpose")
print("Original array:\n", a)
print("Transposed:\n", a.T)  # Switch rows and columns


1. Indexing
a = [10 20 30]
a[0] = 10
a[-1] = 30

b =
 [[1 2]
 [3 4]]
b[0, 1] = 2

2. Slicing
a = [10 20 30 40]
a[1:3] = [20 30]
a[:2] = [10 20]

b =
 [[1 2 3]
 [4 5 6]]
b[:, 1] = [2 5]
b[0, :] = [1 2 3]

3. Boolean Indexing
a = [ 5 10 15 20]
a[a > 10] = [15 20]

4. Fancy Indexing
a = [10 20 30 40]
a[[0, 2]] = [10 30]

5. Reshape & Flatten
Original array:
 [[1 2]
 [3 4]
 [5 6]]
Shape: (3, 2)
Reshaped to 2x3:
 [[1 2 3]
 [4 5 6]]
Flattened array: [1 2 3 4 5 6]

6. Transpose
Original array:
 [[1 2]
 [3 4]
 [5 6]]
Transposed:
 [[1 3 5]
 [2 4 6]]


# Math & Statistics in NumPy

In [7]:
import numpy as np

# 1. Element-wise Arithmetic
print("1. Element-wise Arithmetic")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a =", a)
print("b =", b)
print("a + b =", a + b)     # [5 7 9]
print("a * b =", a * b)     # [4 10 18]
print("a ** 2 =", a ** 2)   # [1 4 9]

# 2. Aggregate Functions
print("\n2. Aggregate Functions")
a = np.array([[1, 2], [3, 4]])
print("a =\n", a)
print("Sum:", np.sum(a))       # 10
print("Mean:", np.mean(a))     # 2.5
print("Std Dev:", np.std(a))   # ~1.118
print("Min:", np.min(a))       # 1
print("Max:", np.max(a))       # 4

# 3. Axis-based Operations
print("\n3. Axis-based Operations")
print("Sum along axis=0 (columns):", np.sum(a, axis=0))  # [4 6]
print("Sum along axis=1 (rows):", np.sum(a, axis=1))     # [3 7]

# 4. Argmax and Argmin
print("\n4. Argmax and Argmin")
a = np.array([10, 5, 7, 20])
print("a =", a)
print("Index of max value (argmax):", np.argmax(a))  # 3
print("Index of min value (argmin):", np.argmin(a))  # 1

1. Element-wise Arithmetic
a = [1 2 3]
b = [4 5 6]
a + b = [5 7 9]
a * b = [ 4 10 18]
a ** 2 = [1 4 9]

2. Aggregate Functions
a =
 [[1 2]
 [3 4]]
Sum: 10
Mean: 2.5
Std Dev: 1.118033988749895
Min: 1
Max: 4

3. Axis-based Operations
Sum along axis=0 (columns): [4 6]
Sum along axis=1 (rows): [3 7]

4. Argmax and Argmin
a = [10  5  7 20]
Index of max value (argmax): 3
Index of min value (argmin): 1


# Broadcasting in NumPy

In [8]:
'''
What is Broadcasting?
> Broadcasting lets NumPy perform operations between arrays with different shapes by stretching the smaller array.

Broadcasting Rules
> If shapes match, no problem.
> If one dimension is 1, stretch that dimension.
> Otherwise, error.

Why use it?
> Broadcasting makes operations faster and memory efficient by avoiding explicit loops.
'''
import numpy as np

# 1. Basic Example - Broadcasting a scalar to an array
print("1. Basic Broadcasting with a scalar")
a = np.array([1, 2, 3])  # Shape (3,)
b = 2                    # Scalar
print("a =", a)
print("b =", b)
print("a + b =", a + b)  # [3 4 5]
print("Note: NumPy treats scalar b as [2, 2, 2] behind the scenes.\n")

# 2. Broadcasting Between Arrays with different shapes
print("2. Broadcasting Between Arrays")
a = np.array([[1], [2], [3]])  # Shape (3,1)
b = np.array([10, 20, 30])     # Shape (3,)
print("a (3x1):\n", a)
print("b (3,):", b)
print("a + b =\n", a + b)
print("Explanation:")
print("- 'a' shape (3,1) broadcasts to (3,3)")
print("- 'b' shape (3,) broadcasts to (1,3), then (3,3)\n")

# 3. More Broadcasting Examples
print("3. More Broadcasting Examples")

# Example 1: (2,3) + (3,) → adds b to each row of a
a = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2,3)
b = np.array([10, 20, 30])             # Shape (3,)
print("a (2x3):\n", a)
print("b (3,):", b)
print("a + b =\n", a + b)

# Example 2: (3,1) + (1,4) → broadcast to (3,4)
a = np.array([[1], [2], [3]])          # Shape (3,1)
b = np.array([[10, 20, 30, 40]])       # Shape (1,4)
print("\na (3x1):\n", a)
print("b (1x4):\n", b)
print("a + b =\n", a + b)

# Example 3: (3,1,2) + (1,4,1) → broadcast to (3,4,2)
a = np.ones((3,1,2))                   # Shape (3,1,2)
b = np.array([[[10], [20], [30], [40]]])  # Shape (1,4,1)
print("\na (3x1x2):\n", a)
print("b (1x4x1):\n", b)
print("a + b =\n", a + b)

1. Basic Broadcasting with a scalar
a = [1 2 3]
b = 2
a + b = [3 4 5]
Note: NumPy treats scalar b as [2, 2, 2] behind the scenes.

2. Broadcasting Between Arrays
a (3x1):
 [[1]
 [2]
 [3]]
b (3,): [10 20 30]
a + b =
 [[11 21 31]
 [12 22 32]
 [13 23 33]]
Explanation:
- 'a' shape (3,1) broadcasts to (3,3)
- 'b' shape (3,) broadcasts to (1,3), then (3,3)

3. More Broadcasting Examples
a (2x3):
 [[1 2 3]
 [4 5 6]]
b (3,): [10 20 30]
a + b =
 [[11 22 33]
 [14 25 36]]

a (3x1):
 [[1]
 [2]
 [3]]
b (1x4):
 [[10 20 30 40]]
a + b =
 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]

a (3x1x2):
 [[[1. 1.]]

 [[1. 1.]]

 [[1. 1.]]]
b (1x4x1):
 [[[10]
  [20]
  [30]
  [40]]]
a + b =
 [[[11. 11.]
  [21. 21.]
  [31. 31.]
  [41. 41.]]

 [[11. 11.]
  [21. 21.]
  [31. 31.]
  [41. 41.]]

 [[11. 11.]
  [21. 21.]
  [31. 31.]
  [41. 41.]]]


# Random Numbers in NumPy

In [9]:
import numpy as np

# 1. Random Floats (between 0 and 1)
print("1. Random Floats (between 0 and 1)")
print("3 random floats:", np.random.rand(3))
print("2x2 array of random floats:\n", np.random.rand(2, 2), "\n")

# 2. Random Integers
print("2. Random Integers")
print("Single int between 1 and 9:", np.random.randint(1, 10))
print("Array of 4 ints between 0 and 4:", np.random.randint(0, 5, size=4), "\n")

# 3. Normal Distribution (mean=0, std=1)
print("3. Normal Distribution (mean=0, std=1)")
print("2x3 array from normal distribution:\n", np.random.randn(2, 3), "\n")

# 4. Fixing Randomness (Seed)
print("4. Fixing Randomness (Seed)")
np.random.seed(42)
print("Same output every time you run (3 random floats):", np.random.rand(3), "\n")

# 5. Shuffle Arrays
print("5. Shuffle Arrays")
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)
np.random.shuffle(arr)
print("Shuffled array:", arr, "\n")

# 6. Random Choice from Array
print("6. Random Choice from Array")
choices = np.array([10, 20, 30, 40])
print("Array to choose from:", choices)
print("Pick 2 random values:", np.random.choice(choices, size=2))


1. Random Floats (between 0 and 1)
3 random floats: [0.43646129 0.33095007 0.33379578]
2x2 array of random floats:
 [[0.2201098  0.72372032]
 [0.82427789 0.60718724]] 

2. Random Integers
Single int between 1 and 9: 1
Array of 4 ints between 0 and 4: [1 0 2 0] 

3. Normal Distribution (mean=0, std=1)
2x3 array from normal distribution:
 [[ 0.42937468  0.14378647  0.85131053]
 [ 0.6640965  -0.7143995   0.57126883]] 

4. Fixing Randomness (Seed)
Same output every time you run (3 random floats): [0.37454012 0.95071431 0.73199394] 

5. Shuffle Arrays
Original array: [1 2 3 4 5]
Shuffled array: [4 2 3 1 5] 

6. Random Choice from Array
Array to choose from: [10 20 30 40]
Pick 2 random values: [30 30]


# Linear Algebra in NumPy

In [10]:
# NumPy provides powerful tools for matrix operations, useful in data science, ML, and simulations.
import numpy as np
from numpy.linalg import det, inv, eig

# 1. Dot Product
print("1. Dot Product")
a = np.array([1, 2])
b = np.array([3, 4])
print("a =", a)
print("b =", b)
print("np.dot(a, b):", np.dot(a, b))  # 1×3 + 2×4 = 11
print("a @ b:", a @ b)               # Same as dot product
print()

# 2. Matrix Multiplication
print("2. Matrix Multiplication")
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A @ B:\n", A @ B)
print("Explanation: Each element is a row of A × column of B\n")

# 3. Transpose of Matrix
print("3. Transpose of Matrix")
print("Original Matrix A:\n", A)
print("Transpose of A:\n", A.T)
print()

# 4. Determinant
print("4. Determinant")
C = np.array([[4, 6], [3, 8]])
print("Matrix C:\n", C)
print("Determinant of C:", det(C))  # 4*8 - 6*3 = 32 - 18 = 14.0
print()

# 5. Inverse of Matrix
print("5. Inverse of Matrix")
D = np.array([[4, 7], [2, 6]])
print("Matrix D:\n", D)
print("Inverse of D:\n", inv(D))
print("Note: Only square matrices with non-zero determinant can be inverted\n")

# 6. Eigenvalues and Eigenvectors
print("6. Eigenvalues & Eigenvectors")
E = np.array([[2, 0], [0, 3]])
values, vectors = eig(E)
print("Matrix E:\n", E)
print("Eigenvalues:", values)
print("Eigenvectors:\n", vectors)

1. Dot Product
a = [1 2]
b = [3 4]
np.dot(a, b): 11
a @ b: 11

2. Matrix Multiplication
Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
A @ B:
 [[19 22]
 [43 50]]
Explanation: Each element is a row of A × column of B

3. Transpose of Matrix
Original Matrix A:
 [[1 2]
 [3 4]]
Transpose of A:
 [[1 3]
 [2 4]]

4. Determinant
Matrix C:
 [[4 6]
 [3 8]]
Determinant of C: 14.000000000000004

5. Inverse of Matrix
Matrix D:
 [[4 7]
 [2 6]]
Inverse of D:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Note: Only square matrices with non-zero determinant can be inverted

6. Eigenvalues & Eigenvectors
Matrix E:
 [[2 0]
 [0 3]]
Eigenvalues: [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]


# Advanced NumPy Operations

In [11]:
import numpy as np

# 1. np.where() — Conditional Logic
print("1. np.where() — Conditional Logic")
a = np.array([10, 15, 20, 25])
result = np.where(a > 18, "High", "Low")
print("Array:", a)
print("Condition: a > 18 →", result)
print()

# 2. np.unique() — Unique Values
print("2. np.unique() — Unique Values")
arr = np.array([1, 2, 2, 3, 4, 4])
print("Original array:", arr)
print("Unique values:", np.unique(arr))
print()

# 3. np.sort() and np.argsort()
print("3. np.sort() and np.argsort()")
a = np.array([3, 1, 2])
print("Original array:", a)
print("Sorted array:", np.sort(a))
print("Indices to sort the array:", np.argsort(a))
print()

# 4. np.clip() — Limit values in array
print("4. np.clip() — Limit values in array")
a = np.array([5, 15, 25])
print("Original array:", a)
print("Clipped (10 to 20):", np.clip(a, 10, 20))
print()

# 5. np.isnan() — Check for NaNs
print("5. np.isnan() — Check for NaNs")
a = np.array([1.0, np.nan, 3.0])
print("Array:", a)
print("Is NaN?:", np.isnan(a))
print()

# 6. np.any() and np.all()
print("6. np.any() and np.all()")
a = np.array([True, False, True])
print("Boolean array:", a)
print("np.any(a):", np.any(a))  # At least one True
print("np.all(a):", np.all(a))  # All must be True
print()

# 7. Stacking Arrays (hstack, vstack)
print("7. Stacking Arrays")
a = np.array([1, 2])
b = np.array([3, 4])
print("a:", a)
print("b:", b)
print("Horizontal stack (hstack):", np.hstack((a, b)))
print("Vertical stack (vstack):\n", np.vstack((a, b)))
print()

# 8. Splitting Arrays
print("8. Splitting Arrays")
arr = np.array([10, 20, 30, 40, 50, 60])
print("Original array:", arr)
print("Split into 3 parts:", np.split(arr, 3))
print()

# 9. Sorting a 2D Array
print("9. Sorting a 2D Array")
arr2d = np.array([[3, 1], [2, 4]])
print("Original 2D array:\n", arr2d)
print("Sorted by rows:\n", np.sort(arr2d, axis=1))
print("Sorted by columns:\n", np.sort(arr2d, axis=0))
print()

# 10. Set Operations
print("10. Set Operations (unique, intersect1d, union1d)")
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
print("a:", a)
print("b:", b)
print("Unique in a:", np.unique(a))
print("Intersection:", np.intersect1d(a, b))
print("Union:", np.union1d(a, b))


1. np.where() — Conditional Logic
Array: [10 15 20 25]
Condition: a > 18 → ['Low' 'Low' 'High' 'High']

2. np.unique() — Unique Values
Original array: [1 2 2 3 4 4]
Unique values: [1 2 3 4]

3. np.sort() and np.argsort()
Original array: [3 1 2]
Sorted array: [1 2 3]
Indices to sort the array: [1 2 0]

4. np.clip() — Limit values in array
Original array: [ 5 15 25]
Clipped (10 to 20): [10 15 20]

5. np.isnan() — Check for NaNs
Array: [ 1. nan  3.]
Is NaN?: [False  True False]

6. np.any() and np.all()
Boolean array: [ True False  True]
np.any(a): True
np.all(a): False

7. Stacking Arrays
a: [1 2]
b: [3 4]
Horizontal stack (hstack): [1 2 3 4]
Vertical stack (vstack):
 [[1 2]
 [3 4]]

8. Splitting Arrays
Original array: [10 20 30 40 50 60]
Split into 3 parts: [array([10, 20]), array([30, 40]), array([50, 60])]

9. Sorting a 2D Array
Original 2D array:
 [[3 1]
 [2 4]]
Sorted by rows:
 [[1 3]
 [2 4]]
Sorted by columns:
 [[2 1]
 [3 4]]

10. Set Operations (unique, intersect1d, union1d)
a: [1

# File I/O in NumPy (Reading/Writing Data)

In [13]:
import numpy as np

# 1. Save to File — np.save(), np.savetxt()
print("1. Save to File")
a = np.array([[1, 2], [3, 4]])
print("Original array a:\n", a)

# Save in binary .npy format
np.save('my_array.npy', a)
print("Saved 'my_array.npy' (binary format)")

# Save in readable text format
np.savetxt('my_array.txt', a)
print("Saved 'my_array.txt' (text format)\n")

# 2. Load from File — np.load(), np.loadtxt()
print("2. Load from File")

# Load binary
b = np.load('my_array.npy')
print("Loaded from 'my_array.npy':\n", b)

# Load from text file
c = np.loadtxt('my_array.txt')
print("Loaded from 'my_array.txt':\n", c)
print()

# 3. Save/Load CSV with delimiter
print("3. Save/Load CSV with delimiter")
d = np.array([[10, 20], [30, 40]])
print("Original array d:\n", d)

# Save as CSV
np.savetxt('data.csv', d, delimiter=',')   #np.savetxt('data.csv', array, delimiter=',')   # Save
print("Saved 'data.csv' with comma delimiter")

# Load CSV
e = np.loadtxt('data.csv', delimiter=',')  #np.loadtxt('data.csv', delimiter=',')          # Load
print("Loaded from 'data.csv':\n", e)
#delimiter=',' tells NumPy to use a comma between values (i.e., make it a CSV).
'''
⚠️ Notes:
CSV doesn't store data types, index, or labels (unlike Excel or Pandas).

NumPy saves just raw numbers — if you want column names, use Pandas.'''

1. Save to File
Original array a:
 [[1 2]
 [3 4]]
Saved 'my_array.npy' (binary format)
Saved 'my_array.txt' (text format)

2. Load from File
Loaded from 'my_array.npy':
 [[1 2]
 [3 4]]
Loaded from 'my_array.txt':
 [[1. 2.]
 [3. 4.]]

3. Save/Load CSV with delimiter
Original array d:
 [[10 20]
 [30 40]]
Saved 'data.csv' with comma delimiter
Loaded from 'data.csv':
 [[10. 20.]
 [30. 40.]]


"\n⚠️ Notes:\nCSV doesn't store data types, index, or labels (unlike Excel or Pandas).\n\nNumPy saves just raw numbers — if you want column names, use Pandas."

# Real-World Examples + Wrap-Up

In [14]:
#Data Normalization (used in ML)
data = np.array([10, 20, 30, 40, 50])
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
print(normalized)  # [0.   0.25 0.5  0.75 1.  ]

[0.   0.25 0.5  0.75 1.  ]


In [15]:
#Moving Average (used in signal processing/finance)
data = np.array([10, 20, 30, 40, 50])
window = 3      #Means we'll average 3 elements at a time.

weights = np.ones(window) / window   #np.ones(3) → [1, 1, 1]  Dividing by 3 → [1/3, 1/3, 1/3] → [0.3333, 0.3333, 0.3333]  This means we give equal weight to each element in the window.

moving_avg = np.convolve(data, weights, mode='valid') 
#Convolution here slides the weights over the data, computing weighted sums. mode='valid' means it only computes the averages where the window fits entirely inside the data (no padding).
print(moving_avg)  # [20. 30. 40.]  First window: (10 + 20 + 30) / 3 = 60 / 3 = 20  Second window: (20 + 30 + 40) / 3 = 90 / 3 = 30  Third window: (30 + 40 + 50) / 3 = 120 / 3 = 40

[20. 30. 40.]


In [17]:
#Euclidean Distance (used in clustering & ML)
'''Euclidean distance is the straight-line distance between two points in space — like measuring with a ruler.
In 2D, it's the distance between two points (𝑥1,𝑦1) and (x2,y2):  
distance=[(x2-x1)^2+(y2-y1)^2]^(1/2)
'''
p1 = np.array([1, 2])   # x1=1, y1=2
p2 = np.array([4, 6])   # x2=4, y2=6

distance = np.linalg.norm(p1 - p2)  #p1 - p2 = [1 - 4, 2 - 6] = [-3, -4]
#np.linalg.norm([-3, -4]):, This gives the length (or magnitude) of the vector [-3, -4], which is the same as:
#[(-3)^2+(-4)^2]^(1/2) = 5.0

print(distance)  # 5.0

5.0


In [18]:
#Boolean Masking (used in filtering data)
data = np.array([5, 10, 15, 20])
filtered = data[data > 10]
print(filtered)  # [15 20]

[15 20]


In [19]:
#Handling Missing Data (NaNs)
data = np.array([1, 2, np.nan, 4])
mean = np.nanmean(data)
print(mean)  # 2.333 (ignores NaN)

2.3333333333333335


# Projects

'''
Mini Project 1: Exam Score Analyzer

Goal:
You are given the exam scores of 20 students as a NumPy array. Your job is to analyze the data using NumPy functions.

Objective:
Analyze a NumPy array of student exam scores to get:
Highest & lowest marks
Class average
Number of students scoring above average
Students who failed (below 40)
Sorted list of scores
Score distribution by range (0-30, 31-60, 61-90, 91-100)
'''

In [21]:
import numpy as np

# 📥 Step 1: Create the Score Data
scores = np.array([56, 78, 90, 34, 65, 88, 92, 47, 59, 73, 
                   81, 66, 39, 54, 68, 77, 49, 60, 94, 85])
print("📥 Student Scores:", scores)

# 📈 Step 2: Find Highest & Lowest Score
max_score = np.max(scores)
min_score = np.min(scores)
print("\n📈 Highest Score:", max_score)
print("📉 Lowest Score:", min_score)

# 📊 Step 3: Find Average Score
average = np.mean(scores)
print("\n📊 Class Average:", average)

# 🧮 Step 4: Count Students Above Average
above_avg = scores[scores > average]
print("\n🧮 Students scoring above average:", above_avg)
print("🔢 Count:", above_avg.size)

# ❌ Step 5: Students Who Failed (< 40)
failed = scores[scores < 40]
print("\n❌ Students who failed:", failed)
print("⚠️ Number of failures:", failed.size)

# 📋 Step 6: Sorted Scores
sorted_scores = np.sort(scores)
print("\n📋 Sorted Scores:", sorted_scores)

# 📊 Step 7: Score Distribution
range_0_30 = np.sum((scores >= 0) & (scores <= 30))
range_31_60 = np.sum((scores >= 31) & (scores <= 60))
range_61_90 = np.sum((scores >= 61) & (scores <= 90))
range_91_100 = np.sum((scores > 90) & (scores <= 100))

print("\n📊 Score Distribution:")
print("  🔹 0–30   :", range_0_30)
print("  🔹 31–60 :", range_31_60)
print("  🔹 61–90 :", range_61_90)
print("  🔹 91–100:", range_91_100)

📥 Student Scores: [56 78 90 34 65 88 92 47 59 73 81 66 39 54 68 77 49 60 94 85]

📈 Highest Score: 94
📉 Lowest Score: 34

📊 Class Average: 67.75

🧮 Students scoring above average: [78 90 88 92 73 81 68 77 94 85]
🔢 Count: 10

❌ Students who failed: [34 39]
⚠️ Number of failures: 2

📋 Sorted Scores: [34 39 47 49 54 56 59 60 65 66 68 73 77 78 81 85 88 90 92 94]

📊 Score Distribution:
  🔹 0–30   : 0
  🔹 31–60 : 8
  🔹 61–90 : 10
  🔹 91–100: 2


'''
Mini Project 2: ML Data Normalizer

Goal:
You’re given a 2D dataset with 3 features:
[Age, Salary (₹), Exam Score] for multiple people.
You’ll preprocess this data using NumPy.

Objective:
Given a dataset (2D array) of features like age, salary, and score:
Normalize all columns (Min-Max scaling)
Apply z-score standardization
Filter rows with score > threshold
Add a new feature column (e.g., age × score)
Split data into training/testing sets (80/20)
'''

In [25]:
import numpy as np

# 📥 Step 1: Create the Dataset
# Rows: [Age, Salary (in ₹1000s), Exam Score]
data = np.array([
    [22, 35, 88],  
    [25, 40, 72],       # means 25 years old, ₹40,000 salary, 72 score.
    [28, 65, 91],
    [23, 30, 56],
    [30, 80, 97],
    [26, 50, 66],
    [29, 60, 85],
    [24, 38, 70]
])
print("📥 Original Data:\n", data)

# ⚖️ Step 2: Min-Max Normalization (0 to 1),   
'''We scale all values between 0 and 1.
     Useful when data values are very different in range (like salary vs age)'''
min_vals = np.min(data, axis=0)
max_vals = np.max(data, axis=0)
norm_data = (data - min_vals) / (max_vals - min_vals)  #Formula
print("\n⚖️ Min-Max Normalized Data (0-1 range):\n", norm_data)

# 📊 Step 3: Z-Score Standardization
'''We adjust the data so:
    > Mean becomes 0
    > Standard deviation becomes 1
      This helps algorithms treat all features equally.
>>Real-Life Example:
Imagine you're comparing:
 Age of people (20–30)
 Salary (30,000–80,000)
Without standardization, salary dominates.
With Z-score standardization:
 Age values become something like: -1.2, 0.3, 1.5
 Salary values become something like: -0.9, 0.1, 1.0
✅ Now both features are in the same range, and the model makes better decisions.'''
mean_vals = np.mean(data, axis=0)
std_vals = np.std(data, axis=0)
z_score_data = (data - mean_vals) / std_vals
print("\n📊 Z-Score Standardized Data:\n", z_score_data)

# 🎯 Step 4: Filter Rows with Exam Score > 80, We find students who scored more than 80 in the exam.
high_scorers = data[data[:, 2] > 80]
print("\n🎯 Students with Exam Score > 80:\n", high_scorers)

# ➕ Step 5: Add a New Feature — Age × Score
'''We create a new value for each person:
    > Multiply their age with their score
      This may help find how much age affects performance.'''

age_score_product = (data[:, 0] * data[:, 2]).reshape(-1, 1)
enhanced_data = np.hstack((data, age_score_product))
print("\n➕ Data with New Feature (Age × Score):\n", enhanced_data)

# 🧪 Step 6: Split into Training and Testing Sets (80/20)
'''We split the data randomly:
    >80% used to train a model
    >20% used to test the model
     This is done to check how well a model learns and predicts.'''

np.random.seed(42)  # For reproducibility
indices = np.random.permutation(len(data))
train_size = int(0.8 * len(data))
train_idx = indices[:train_size]
test_idx = indices[train_size:]
train_data = data[train_idx]
test_data = data[test_idx]
print("\n🧪 Training Data (80%):\n", train_data)
print("\n🧪 Testing Data (20%):\n", test_data)

📥 Original Data:
 [[22 35 88]
 [25 40 72]
 [28 65 91]
 [23 30 56]
 [30 80 97]
 [26 50 66]
 [29 60 85]
 [24 38 70]]

⚖️ Min-Max Normalized Data (0-1 range):
 [[0.         0.1        0.7804878 ]
 [0.375      0.2        0.3902439 ]
 [0.75       0.7        0.85365854]
 [0.125      0.         0.        ]
 [1.         1.         1.        ]
 [0.5        0.4        0.24390244]
 [0.875      0.6        0.70731707]
 [0.25       0.16       0.34146341]]

📊 Z-Score Standardized Data:
 [[-1.4284046  -0.91180198  0.74465368]
 [-0.32254297 -0.60271656 -0.4618738 ]
 [ 0.78331865  0.94271052  0.97087759]
 [-1.05978406 -1.2208874  -1.66840129]
 [ 1.52055974  1.86996677  1.42332539]
 [ 0.04607757  0.01545427 -0.91432161]
 [ 1.15193919  0.63362511  0.51842978]
 [-0.69116352 -0.72635073 -0.61268974]]

🎯 Students with Exam Score > 80:
 [[22 35 88]
 [28 65 91]
 [30 80 97]
 [29 60 85]]

➕ Data with New Feature (Age × Score):
 [[  22   35   88 1936]
 [  25   40   72 1800]
 [  28   65   91 2548]
 [  23   30   56

'''
Mini Project: Logic Gate Simulator + Verification Loop (VLSI-Design and Verification)
Objective
> Design: Simulate basic logic gates (AND, OR, NOT, XOR) on multiple input vectors using   NumPy arrays.
> Verification: Compare the simulator output against expected output vectors.
> Loop: Run multiple test vectors and report pass/fail for each.
'''

In [27]:
import numpy as np

# Step 1: Define logic gates using NumPy bitwise operations
def AND_gate(a, b):
    return np.bitwise_and(a, b)

def OR_gate(a, b):
    return np.bitwise_or(a, b)

def NOT_gate(a):
    return np.bitwise_not(a) & 1  # Keep last bit only (0 or 1)

def XOR_gate(a, b):
    return np.bitwise_xor(a, b)

# Step 2: Prepare test inputs and expected outputs
input_a = np.array([0, 0, 1, 1])
input_b = np.array([0, 1, 0, 1])

expected_and = np.array([0, 0, 0, 1])
expected_or  = np.array([0, 1, 1, 1])
expected_xor = np.array([0, 1, 1, 0])
expected_not_a = np.array([1, 1, 0, 0])

# Step 3: Function to run gate and verify outputs
'''
This function runs a logic gate function on given inputs and checks if the output matches what you expect.
 Inputs to verify_gate:
  gate_func: The logic gate function to test (e.g., AND_gate).
  input1: First input array (like [0, 0, 1, 1]).
  input2: Second input array if needed (like [0, 1, 0, 1]).
  expected_output: What you expect the gate to return (like [0, 0, 0, 1] for AND).
 What it does inside:
  Calls the logic gate function with inputs.
  Prints the inputs and outputs so you can see the results.
  If an expected output is provided, it compares the output to the expected output.
  Prints "PASS" if output matches expected, or "FAIL" if it doesn’t.
This is like a little tester that checks if the gate works correctly.'''
def verify_gate(gate_func, input1, input2=None, expected_output=None):
    if input2 is not None:
        output = gate_func(input1, input2)
    else:
        output = gate_func(input1)

    print("Input 1:       ", input1)
    if input2 is not None:
        print("Input 2:       ", input2)
    print("Gate Output:   ", output)
    if expected_output is not None:
        print("Expected Output:", expected_output)
        # Check correctness
        if np.array_equal(output, expected_output):
            print("Verification: PASS ✅\n")
        else:
            print("Verification: FAIL ❌\n")
    return output

# Step 4: Run tests and print results
print("AND Gate Verification:")
verify_gate(AND_gate, input_a, input_b, expected_and)

print("OR Gate Verification:")
verify_gate(OR_gate, input_a, input_b, expected_or)

print("XOR Gate Verification:")
verify_gate(XOR_gate, input_a, input_b, expected_xor)

print("NOT Gate Verification (on input A):")
verify_gate(NOT_gate, input_a, expected_output=expected_not_a)

AND Gate Verification:
Input 1:        [0 0 1 1]
Input 2:        [0 1 0 1]
Gate Output:    [0 0 0 1]
Expected Output: [0 0 0 1]
Verification: PASS ✅

OR Gate Verification:
Input 1:        [0 0 1 1]
Input 2:        [0 1 0 1]
Gate Output:    [0 1 1 1]
Expected Output: [0 1 1 1]
Verification: PASS ✅

XOR Gate Verification:
Input 1:        [0 0 1 1]
Input 2:        [0 1 0 1]
Gate Output:    [0 1 1 0]
Expected Output: [0 1 1 0]
Verification: PASS ✅

NOT Gate Verification (on input A):
Input 1:        [0 0 1 1]
Gate Output:    [1 1 0 0]
Expected Output: [1 1 0 0]
Verification: PASS ✅



array([1, 1, 0, 0])